### ISSUE TITLE
Disable wicket outputting internal jquery version

### ISSUE THREAD

**Issue by steveswinsburg** [steveswinsburg/sakai-widgets#28]
Throws 404's when inline. jQuery is already there.

![screen shot 2016-07-04 at 9 36 46 pm](https://cloud.githubusercontent.com/assets/129129/16559312/79856fba-422f-11e6-895e-3eddec72b66f.png)

**Comment by steveswinsburg** [comment]
@mgolden-noodle I can't reproduce this locally. I only get good response codes. I am wondering if maybe it is a webserver mapping that means that the .js is not directly web accessible?
URLs I see are:

```
http://localhost:8080/portal/site/7ccaa65e-f896-440d-8342-66e392123565/page/wicket/resource/org.apache.wicket.ajax.AbstractDefaultAjaxBehavior/res/js/wicket-event-jquery-ver-1421756394000.js
```

and

```
http://localhost:8080/portal/site/7ccaa65e-f896-440d-8342-66e392123565/page/wicket/resource/org.apache.wicket.resource.JQueryResourceReference/jquery/jquery-1.11.1-ver-1421756394000.js
```

etc.

Can you get the full URLs on your server?

Note that I could do something like this:
http://stackoverflow.com/questions/22324500/wicket-6-remove-jquery-reference

**Comment by steveswinsburg** [comment]
Ok I have done that and switched the ones that actually need jquery over to use the Sakai webjars version. Those errors should be suppressed now.

**Comment by mgolden-noodle** [comment]
For future reference, if you need to see something on our dev server, the URL Is sakai.noodle-partners.com:8080/portal (or 7070 also works).

**Comment by mgolden-noodle** [comment]
Actually, I am still seeing these 404s, but asking for "empty" not
jquery-ui.  I've attached a screenshot. (Note: it's sorted by status, not
time, so all the 404s are at the top.

Mitch Golden
CTO
Noodle Partners, Inc.
59 Chelsea Piers, Suite 200, New York, NY, 10011
+1 646 289 7834 | mgolden@noodle.com | noodle-partners.com

**Comment by steveswinsburg** [comment]
Ok this sounds like a web server issue then. To suppress the jquery
internal reference I replaced it with an empty.js file as per the
recommendation. This is mounted and accessible but not in your particular
case. Maybe there is something to do with direct access of resources since
it is in WEB-INF? You might need to allow WEB-INF/classes through as that
is where Wicket has all of it's resources.

**Comment by mgolden-noodle** [comment]
Not sure I understand. What are you saying I should do?

## 

Mitch Golden
CTO, Noodle Partners

**Comment by steveswinsburg** [comment]
Check if there is some rule on your webserver preventing access to the
WEB-INF folder.

**Comment by mgolden-noodle** [comment]
I am not running a webserver at all - it's just tomcat. Where would I check
for a rule like that?

Mitch Golden
CTO
Noodle Partners, Inc.
59 Chelsea Piers, Suite 200, New York, NY, 10011
+1 646 289 7834 | mgolden@noodle.com | noodle-partners.com

**Comment by steveswinsburg** [comment]
Ah sorry it's like this by default. Let me see if I can move the resources to somewhere publicly accessible. Unsure why it works for the other resources in Wicket.

**Comment by mgolden-noodle** [comment]
Did you make a change? Should I pull and redeploy?

Mitch Golden
CTO
Noodle Partners, Inc.
59 Chelsea Piers, Suite 200, New York, NY, 10011
+1 646 289 7834 | mgolden@noodle.com | noodle-partners.com

**Comment by steveswinsburg** [comment]
Ok I can see the problem. It is rendering the wrong URL when it is inlined. It is rendering:
`.wicket/resource/org.sakaiproject.widgets.sitemembers.WidgetApplication/empty-ver-1468406474000.js` - it should have a context path.

**Comment by steveswinsburg** [comment]
OK this is fixed in latest commit. References should now be correct and the 404s and console errors should be gone.

**Comment by mgolden-noodle** [comment]
Great - will deploy.

Mitch Golden
CTO
Noodle Partners, Inc.
59 Chelsea Piers, Suite 200, New York, NY, 10011
+1 646 289 7834 | mgolden@noodle.com | noodle-partners.com
